### ISSUE TITLE
Exec proxy not found

### ISSUE THREAD

**Issue by Muhan95** [DynamicRemo/WifiApp#2]
Hi, I've cloned your repo exactly as it is - I had to install the wifiwizard and keyboard plugins separately for some reason. When I try to run the app I get the error:

Error: exec proxy not found for :: WifiWizard :: startScan

I get the same error when I try to configure WifiWizard myself on any other project too. My phonegap version is 6.2.0. Any ideas?

@DynamicRemo

**Comment by DynamicRemo** [comment]
@Muhan95 yes you have to install the plugins explicitly, every time you cloning of repository.

This error have already been catered in the repository [WifiApp](https://github.com/DynamicRemo/WifiApp) and also believes that Phonegap's latest versions are also supported by WifiWizard Plugin. The thing is, Cordova/Phonegap apps need some extra milliseconds to get ready while you are using some third party plugins just like "WifiWizard". That's the reason why as soon as app starts your variable $scope.startWifi tries to get initialized before even the plugin is ready.

A simple hack is to delay your initialization by some seconds using the cool circular slider and you will be good to go. Cheers :)

**Comment by Muhan95** [comment]
@DynamicRemo I have tried adding a delay before running the wifiwizard functions but this only gives me the same result. Even when I try to run your WifiApp demo as it is, I get the same error. 

I'm wondering if the version of wifi wizard I have is corrupted as other third party plugins work fine, could you push the plugin files you have to a git repository so I can clone them? Or do you have any other ideas?

Thanks

**Comment by DynamicRemo** [comment]
@Muhan95 please have a look at the repository, i just pushed Node Modules, Plugin and Platform Folder for you. Sorry for the late respone. 

Hope this will help you out, Cheers ;)

**Comment by Muhan95** [comment]
@DynamicRemo I've now used the exact same setup as you and I still get the error:
Error: exec proxy not found for :: WifiWizard :: startScan

Are you on skype by any chance? I'd be more than willing to pay you for your time if you can help me get this to work.
